import type { Category, Product, Review } from "./types";

export const RESTAURANT = {
  name: "Muestra",
  tagline: "Brunch & Burgers de autor",
  neighborhood: "Sabaneta · Medellín",
  address: "Cra. 45 #72 Sur-10, Sabaneta",
  phone: "+57 300 000 0000",
  whatsapp: "573000000000", // demo number
  hours: "Mar–Dom · 11:00 a 21:30",
  rating: 4.8,
  reviewCount: 1247,
  ig: "muestra",
};

export const CATEGORIES: Category[] = [
  { id: "top", name: "Los favoritos", emoji: "★" },
  { id: "burgers", name: "Hamburguesas", emoji: "🍔" },
  { id: "brunch", name: "Brunch", emoji: "🍳" },
  { id: "alitas", name: "Alitas", emoji: "🍗" },
  { id: "sides", name: "Para picar", emoji: "🍟" },
  { id: "postres", name: "Postres", emoji: "🍰" },
  { id: "bebidas", name: "Bebidas", emoji: "🥤" },
];

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=70`;

const cheeseGroup = {
  id: "punto",
  label: "Término de la carne",
  type: "single" as const,
  required: true,
  options: [
    { id: "medio", label: "Término medio", price: 0 },
    { id: "tresc", label: "Tres cuartos", price: 0 },
    { id: "bien", label: "Bien cocida", price: 0 },
  ],
};

const extrasGroup = {
  id: "extras",
  label: "Adiciones",
  type: "multi" as const,
  max: 5,
  options: [
    { id: "tocineta", label: "Extra tocineta", price: 4900 },
    { id: "queso", label: "Extra queso cheddar", price: 3500 },
    { id: "carne", label: "Carne adicional 120g", price: 8900 },
    { id: "huevo", label: "Huevo frito", price: 2900 },
    { id: "aguacate", label: "Aguacate", price: 3900 },
  ],
};

const sauceGroup = {
  id: "salsas",
  label: "Salsas de la casa",
  type: "multi" as const,
  max: 3,
  options: [
    { id: "casa", label: "Salsa Muestra", price: 0 },
    { id: "bbq", label: "BBQ ahumada", price: 0 },
    { id: "chipotle", label: "Chipotle", price: 0 },
    { id: "ranch", label: "Ranch", price: 1500 },
  ],
};

export const PRODUCTS: Product[] = [
  {
    id: "clasica",
    name: "La Muestra Clásica",
    categoryId: "burgers",
    description:
      "Doble carne madurada 120g, cheddar fundido, tocineta, tomate, cebolla caramelizada y salsa de la casa en pan brioche artesanal.",
    price: 28900,
    image: img("photo-1568901346375-23c9450c58cd"),
    tags: ["top"],
    prepMin: 16,
    kcal: 890,
    popularity: 98,
    modifiers: [cheeseGroup, extrasGroup, sauceGroup],
    pairWith: ["papas-trufa", "malteada", "aros"],
  },
  {
    id: "smash",
    name: "Smash Doble",
    categoryId: "burgers",
    description:
      "Dos smash patties crujientes, doble cheddar, pepinillos y salsa smash. Intensa y jugosa.",
    price: 26900,
    image: img("photo-1550547660-d9450f859349"),
    tags: ["top", "picante"],
    prepMin: 14,
    kcal: 780,
    popularity: 94,
    modifiers: [extrasGroup, sauceGroup],
    pairWith: ["papas-trufa", "limonada"],
  },
  {
    id: "bbq-bacon",
    name: "BBQ Bacon Ranch",
    categoryId: "burgers",
    description:
      "Carne angus, doble tocineta, aros de cebolla crocantes, cheddar y BBQ ahumada.",
    price: 30900,
    image: img("photo-1571091718767-18b5b1457add"),
    tags: [],
    prepMin: 17,
    kcal: 940,
    popularity: 82,
    modifiers: [cheeseGroup, extrasGroup, sauceGroup],
    pairWith: ["aros", "malteada"],
  },
  {
    id: "veggie",
    name: "Green Garden",
    categoryId: "burgers",
    description:
      "Hamburguesa de garbanzo y remolacha, aguacate, rúgula, tomate asado y alioli vegano.",
    price: 25900,
    image: img("photo-1520072959219-c595dc870360"),
    tags: ["veg", "nuevo"],
    prepMin: 15,
    kcal: 560,
    popularity: 71,
    modifiers: [sauceGroup],
    pairWith: ["papas-trufa", "limonada"],
  },
  {
    id: "huevos-benedict",
    name: "Huevos Benedictinos",
    categoryId: "brunch",
    description:
      "Muffin inglés, jamón serrano, huevos pochados y holandesa de la casa con toque de cebollín.",
    price: 24900,
    image: img("photo-1608039829572-78524f79c4c7"),
    tags: ["top"],
    prepMin: 18,
    kcal: 620,
    popularity: 90,
    pairWith: ["capuccino", "jugo"],
  },
  {
    id: "pancakes",
    name: "Pancakes de la Casa",
    categoryId: "brunch",
    description:
      "Torre de tres pancakes esponjosos, mantequilla de maple, frutos rojos y crema batida.",
    price: 21900,
    image: img("photo-1567620905732-2d1ec7ab7445"),
    tags: ["veg"],
    prepMin: 14,
    kcal: 710,
    popularity: 85,
    pairWith: ["capuccino", "jugo"],
  },
  {
    id: "avocado-toast",
    name: "Avocado Toast",
    categoryId: "brunch",
    description:
      "Pan de masa madre, aguacate, huevo pochado, semillas, rúgula y aceite de oliva.",
    price: 19900,
    image: img("photo-1482049016688-2d3e1b311543"),
    tags: ["veg", "singluten"],
    prepMin: 12,
    kcal: 430,
    popularity: 68,
    pairWith: ["jugo", "capuccino"],
  },
  {
    id: "alitas-bbq",
    name: "Alitas BBQ (8u)",
    categoryId: "alitas",
    description:
      "Ocho alitas glaseadas en BBQ ahumada de la casa, con dip ranch y bastones de apio.",
    price: 27900,
    image: img("photo-1608039755401-742074f0548d"),
    tags: ["top"],
    prepMin: 20,
    kcal: 820,
    popularity: 88,
    pairWith: ["papas-trufa", "cerveza"],
  },
  {
    id: "alitas-picantes",
    name: "Alitas Buffalo (8u)",
    categoryId: "alitas",
    description:
      "Buffalo picante nivel medio, crujientes por fuera y jugosas por dentro. Para los valientes.",
    price: 27900,
    image: img("photo-1527477396000-e27163b481c2"),
    tags: ["picante"],
    prepMin: 20,
    kcal: 800,
    popularity: 79,
    pairWith: ["limonada", "cerveza"],
  },
  {
    id: "papas-trufa",
    name: "Papas a la Trufa",
    categoryId: "sides",
    description:
      "Papas rústicas, aceite de trufa, parmesano y perejil. El acompañante perfecto.",
    price: 15900,
    image: img("photo-1573080496219-bb080dd4f877"),
    tags: ["veg", "top"],
    prepMin: 10,
    kcal: 480,
    popularity: 92,
    pairWith: ["clasica", "cerveza"],
  },
  {
    id: "aros",
    name: "Aros de Cebolla",
    categoryId: "sides",
    description: "Aros crocantes empanizados a mano, con dip chipotle.",
    price: 13900,
    image: img("photo-1639024471283-03518883512d"),
    tags: ["veg"],
    prepMin: 9,
    kcal: 390,
    popularity: 74,
    pairWith: ["bbq-bacon"],
  },
  {
    id: "nachos",
    name: "Nachos Cargados",
    categoryId: "sides",
    description:
      "Totopos, cheddar fundido, guacamole, pico de gallo, jalapeños y crema agria.",
    price: 22900,
    image: img("photo-1513456852971-30c0b8199d4d"),
    tags: ["veg", "picante"],
    prepMin: 12,
    kcal: 690,
    popularity: 77,
    pairWith: ["cerveza", "limonada"],
  },
  {
    id: "brownie",
    name: "Brownie con Helado",
    categoryId: "postres",
    description:
      "Brownie tibio de chocolate belga, helado de vainilla y salsa de caramelo salado.",
    price: 16900,
    image: img("photo-1606313564200-e75d5e30476c"),
    tags: ["veg", "top"],
    prepMin: 8,
    kcal: 620,
    popularity: 86,
    pairWith: ["capuccino"],
  },
  {
    id: "cheesecake",
    name: "Cheesecake de Frutos Rojos",
    categoryId: "postres",
    description: "Cremoso, sobre base de galleta, con coulis de frutos rojos.",
    price: 15900,
    image: img("photo-1533134242443-d4fd215305ad"),
    tags: ["veg"],
    prepMin: 5,
    kcal: 540,
    popularity: 70,
    pairWith: ["capuccino"],
  },
  {
    id: "malteada",
    name: "Malteada de Oreo",
    categoryId: "bebidas",
    description: "Malteada cremosa de Oreo con crema batida y topping.",
    price: 14900,
    image: img("photo-1572490122747-3968b75cc699"),
    tags: ["veg", "top"],
    prepMin: 6,
    kcal: 560,
    popularity: 83,
    pairWith: ["clasica", "smash"],
  },
  {
    id: "limonada",
    name: "Limonada de Coco",
    categoryId: "bebidas",
    description: "Refrescante limonada de coco natural. Un clásico paisa.",
    price: 9900,
    image: img("photo-1497534446932-c925b458314a"),
    tags: ["veg", "singluten"],
    prepMin: 5,
    kcal: 210,
    popularity: 80,
    pairWith: ["smash", "alitas-picantes"],
  },
  {
    id: "capuccino",
    name: "Capuccino de Origen",
    categoryId: "bebidas",
    description: "Café de origen antioqueño, leche cremada y arte latte.",
    price: 8900,
    image: img("photo-1572442388796-11668a67e53d"),
    tags: ["veg", "singluten"],
    prepMin: 5,
    kcal: 120,
    popularity: 75,
    pairWith: ["brownie", "pancakes"],
  },
  {
    id: "jugo",
    name: "Jugo Natural del Día",
    categoryId: "bebidas",
    description: "Jugo natural exprimido del día. Pregunta por la fruta.",
    price: 8900,
    image: img("photo-1600271886742-f049cd451bba"),
    tags: ["veg", "singluten"],
    prepMin: 5,
    kcal: 160,
    popularity: 66,
    pairWith: ["avocado-toast", "huevos-benedict"],
  },
  {
    id: "cerveza",
    name: "Cerveza Artesanal",
    categoryId: "bebidas",
    description: "Cerveza artesanal local, rotativa. Pregunta por la del día.",
    price: 12900,
    image: img("photo-1608270586620-248524c67de9"),
    tags: [],
    prepMin: 2,
    kcal: 180,
    popularity: 72,
    pairWith: ["alitas-bbq", "nachos"],
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    name: "Valentina O.",
    avatar: "https://i.pravatar.cc/120?img=47",
    rating: 5,
    text: "La mejor hamburguesa de Sabaneta, sin discusión. Pedí directo por la web y llegó calientica en 25 min. Adiós Rappi 😅",
    date: "hace 3 días",
    source: "Google",
  },
  {
    id: "r2",
    name: "Andrés M.",
    avatar: "https://i.pravatar.cc/120?img=12",
    rating: 5,
    text: "El brunch los domingos es un planazo. Los huevos benedictinos están de otro nivel. Volvimos por los puntos 🔥",
    date: "hace 1 semana",
    source: "Google",
  },
  {
    id: "r3",
    name: "Laura Q.",
    avatar: "https://i.pravatar.cc/120?img=32",
    rating: 5,
    text: "Pedí por WhatsApp y me llegó todo perfecto, tal cual lo personalicé. La malteada de Oreo es adictiva.",
    date: "hace 2 semanas",
    source: "Instagram",
  },
  {
    id: "r4",
    name: "Sebastián R.",
    avatar: "https://i.pravatar.cc/120?img=15",
    rating: 5,
    text: "Ambiente increíble y atención de 10. Las alitas BBQ son las mejores que he probado en el Valle de Aburrá.",
    date: "hace 3 semanas",
    source: "Google",
  },
  {
    id: "r5",
    name: "Daniela P.",
    avatar: "https://i.pravatar.cc/120?img=45",
    rating: 5,
    text: "Escaneé el QR de la mesa y pedí sin esperar al mesero. Rapidísimo y súper fácil. ¡Ojalá todos los restaurantes tuvieran esto!",
    date: "hace 5 días",
    source: "Google",
  },
  {
    id: "r6",
    name: "Julián C.",
    avatar: "https://i.pravatar.cc/120?img=13",
    rating: 5,
    text: "Pedí para recoger y estuvo listo justo a tiempo. La Smash Doble es una locura. Ya van 6 pedidos este mes 😅",
    date: "hace 1 semana",
    source: "Instagram",
  },
  {
    id: "r7",
    name: "Mariana G.",
    avatar: "https://i.pravatar.cc/120?img=25",
    rating: 5,
    text: "El programa de puntos me tiene enganchada. Redimí un postre gratis en mi cumpleaños, un detallazo.",
    date: "hace 2 semanas",
    source: "Google",
  },
  {
    id: "r8",
    name: "Felipe A.",
    avatar: "https://i.pravatar.cc/120?img=52",
    rating: 5,
    text: "Domicilio en 22 minutos, calientico y bien empacado. Cero intermediarios, se nota en el precio.",
    date: "hace 4 días",
    source: "Google",
  },
];

export const FAQS = [
  {
    q: "¿Hacen domicilios? ¿A qué zonas?",
    a: "Sí. Cubrimos Sabaneta, Envigado y sur de Medellín. El costo del domicilio se calcula automáticamente según tu dirección al momento de ordenar.",
  },
  {
    q: "¿Cuánto tarda mi pedido?",
    a: "En promedio 25–35 minutos a domicilio y 15 minutos para recoger. Verás el tiempo estimado en tiempo real cuando ordenes.",
  },
  {
    q: "¿Qué medios de pago aceptan?",
    a: "Nequi, Daviplata, Bancolombia QR, PSE, tarjeta y efectivo contra entrega. Todo desde la misma web, sin salir de la conversación.",
  },
  {
    q: "¿Puedo personalizar mi hamburguesa?",
    a: "¡Claro! Cada producto permite agregar adiciones, elegir término, salsas y dejar notas especiales para la cocina.",
  },
  {
    q: "¿Cómo funciona el programa de puntos?",
    a: "Ganas 1 punto por cada $1.000 en pedidos directos. Acumula y redime por productos gratis, postres y sorpresas de cumpleaños.",
  },
];
